language: python
python:
    - "2.7"

install:
    - pip install -r test_requirements.txt
    - pip install coveralls

script:
    - python setup.py develop
    - nosetests --with-coverage --cover-package=cloudshell

after_success:
    coveralls
